### ISSUE TITLE
Moving to the last marker suddenly stops

### ISSUE THREAD

**Issue by mobilerobotics1111** [hrnr/m-explore#81]
It moves to the last goal and suddenly stops.

/move_base/result
Looking at the results, usually in the middle

```
header:
   seq: 4
   stamp:
     secs: 1699071376
     nsecs: 27268879
   frame_id: ''
status:
   goal_id:
     stamp:
       secs: 1699071373
       nsecs: 430295588
     id: "/explore-5-1699071373.430295588"
   status: 2
   text: "This goal was canceled because another goal was recieved by the simple action server"
result:
```

As above, there is content in the text

```
header:
   seq: 5
   stamp:
     secs: 1699071378
     nsecs: 529019329
   frame_id: ''
status:
   goal_id:
     stamp:
       secs: 1699071375
       nsecs: 927466009
     id: "/explore-6-1699071375.927466009"
   status: 2
   text: ''
result:
```

When moving to the last marker, the text is empty.

I also want to check if the navigation has ended. what should I do?
